# SwiftLint configuration

# Line length thresholds
line_length:
  warning: 300
  error: 500

custom_rules:
  no_print:
    name: "Avoid print()"
    regex: "print\\s*\\("
    message: "Use debugPrint() instead of print() to avoid print statements during runtime in the release version."
    severity: warning